spring.application.name=Spring_AI-1

server.port=8081



# ===========================
# Groq (OpenAI Compatible)
# ===========================
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.model=llama-3.3-70b-versatile



logging.level.org.springframework.ai=DEBUG


# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_chat_memory
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver


spring.ai.chat.memory.repository.jdbc.initialize-schema = always