spring.application.name=Spring_AI-1

server.port=8081



# ===========================
# Groq (OpenAI Compatible)
# ===========================
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.model=llama-3.3-70b-versatile



logging.level.org.springframework.ai=DEBUG